sonar.verbose=true
sonar.organization=saidemy01-ki
sonar.projectKey=saidemy01-ki_spark-java
sonar.projectName=spark-java
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
